import type { Prospect } from './types';

export const prospects: Prospect[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    company: 'Innovate Inc.',
    industry: 'Tech',
    location: 'San Francisco, CA',
    contact: {
      email: 'alice.j@innovate.com',
      website: 'innovate.com',
    },
    status: 'new',
    lastContacted: null,
    onlinePresence: 'Active on LinkedIn, company blog focuses on AI.',
    avatar: 'https://picsum.photos/seed/1/100/100',
  },
  {
    id: '2',
    name: 'Bob Williams',
    company: 'HealthWell',
    industry: 'Healthcare',
    location: 'New York, NY',
    contact: {
      email: 'bob@healthwell.org',
      website: 'healthwell.org',
    },
    status: 'contacted',
    lastContacted: '2024-07-20T10:30:00Z',
    onlinePresence: 'Hospital network with a patient portal.',
    avatar: 'https://picsum.photos/seed/2/100/100',
  },
  {
    id: '3',
    name: 'Charlie Brown',
    company: 'MoneyTree',
    industry: 'Finance',
    location: 'Chicago, IL',
    contact: {
      email: 'charlie@moneytree.com',
      website: 'moneytree.com',
    },
    status: 'interested',
    lastContacted: '2024-07-18T14:00:00Z',
    onlinePresence: 'Fintech startup with a new investment app.',
    avatar: 'https://picsum.photos/seed/3/100/100',
  },
  {
    id: '4',
    name: 'Diana Prince',
    company: 'Shopify',
    industry: 'E-commerce',
    location: 'Ottawa, ON',
    contact: {
      email: 'diana.p@shopify.com',
      website: 'shopify.com',
    },
    status: 'replied',
    lastContacted: '2024-07-21T09:00:00Z',
    onlinePresence: 'Major e-commerce platform.',
    avatar: 'https://picsum.photos/seed/4/100/100',
  },
  {
    id: '5',
    name: 'Ethan Hunt',
    company: 'LearnSphere',
    industry: 'Education',
    location: 'London, UK',
    contact: {
      email: 'ethan.hunt@learnsphere.edu',
      website: 'learnsphere.edu',
    },
    status: 'not_interested',
    lastContacted: '2024-07-15T11:45:00Z',
    onlinePresence: 'Online learning platform for universities.',
    avatar: 'https://picsum.photos/seed/5/100/100',
  },
  {
    id: '6',
    name: 'Fiona Glenanne',
    company: 'AdVantage',
    industry: 'Marketing',
    location: 'Los Angeles, CA',
    contact: {
      email: 'fiona@advantage.agency',
      website: 'advantage.agency',
    },
    status: 'new',
    lastContacted: null,
    onlinePresence: 'Digital marketing agency with strong case studies.',
    avatar: 'https://picsum.photos/seed/6/100/100',
  },
  {
    id: '7',
    name: 'George Costanza',
    company: 'Vandelay Industries',
    industry: 'Real Estate',
    location: 'New York, NY',
    contact: {
      email: 'george@vandelay.com',
      website: 'vandelay.com',
    },
    status: 'contacted',
    lastContacted: '2024-07-22T16:20:00Z',
    onlinePresence: 'Commercial real estate firm.',
    avatar: 'https://picsum.photos/seed/7/100/100',
  },
  {
    id: '8',
    name: 'Hannah Abbott',
    company: 'MedTech Solutions',
    industry: 'Healthcare',
    location: 'Boston, MA',
    contact: {
      email: 'h.abbott@medtech.io',
      website: 'medtech.io',
    },
    status: 'interested',
    lastContacted: '2024-07-19T12:00:00Z',
    onlinePresence: 'Startup developing new medical imaging software.',
    avatar: 'https://picsum.photos/seed/8/100/100',
  },
];
